from cs1robots import *
create_world()
hubo = Robot()
hubo.set_trace("blue")
hubo.set_pause(2)
hubo.move()
hubo.move()
hubo.turn_left()
hubo.move()
hubo.move()
hubo.turn_left()
hubo.move()
hubo.move()
hubo.turn_left()
hubo.move()
hubo.move()
